name: deploy-myapp-aws-ebs
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    strategy:
      matrix:
        env: [Production]
    uses: ./.github/workflows/deploy_aws_ebs_template.yaml
    with:
      AWS_EBSTALK_APPLICATION_NAME: ${{ vars.AWS_EBSTALK_APPLICATION_NAME }}
      AWS_EBSTALK_ENVIRONMENT_NAME: ${{ vars.AWS_EBSTALK_ENVIRONMENT_NAME }}
      AWS_EBSTALK_REGION: ${{ vars.AWS_EBSTALK_REGION }}
      RUNNER: ubuntu-latest
      ENVIRONMENT: Production
      DEPLOYMENT_STORAGE_ACCOUNT_NAME: ${{ vars.DEPLOYMENT_STORAGE_ACCOUNT_NAME }}
      EB_APP_VERSION_LABEL: ${{ vars.EB_APP_VERSION_LABEL }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    